repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.6
  hooks:
    - id: ruff
      args: [check, ., --output-format=github]
    - id: ruff-format
      args: [format, ., --check, --diff]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  -   id: mypy
      args: [--explicit-package-bases, src, ]
      
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
  -   id: bandit
      args: ["-r", ".", "--exclude", "./tests"]